---
title: "Draft Exploration"
author: "Chase Bookin"
date: "March 21, 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(tidycensus)
library(ggthemes)
library(ggplot2)
library(janitor)
library(dplyr)
library(gt)
library(readxl)
library(sf)
library(scales)
library(magrittr)
library(haven)
library(infer)
library(Lahman)
library(xml2)
library(rvest)
library(DataCombine)
```

```{r, include=FALSE}
war <- read_csv("data/war.csv")
```


```{r, include=FALSE}

draft <- read_csv("data/draft_register.csv") %>%
  clean_names()

# grouping war data by player and summing career games played and war

war_joined <- war %>%
  group_by(mlb_ID) %>%
  summarize(g = sum(G),
            war = sum(as.numeric(WAR)))

```

```{r, include=FALSE}

# joined draft and war data by player mlb ID, then mutated teamname to condense
# the Angel's team names into a single team. I then arranged the data by year,
# grouped by player_id, and mutated a column called draft_mumber based on the
# row number (or occurence of that player's id) in the data. I did this because
# I wanted a column that tells for each draft a player is selected in, that it
# is the nth time that player has been selected. For example, if a player turns
# down the draft out of high school, after a year of junior college, and gets
# drafted after his junior year the draft_numb column should say 1,2,3 for each
# respective draft.

master <- draft %>%
  left_join(war_joined, by = c("mlbid" = "mlb_ID")) %>%
  mutate(teamname = as.factor(case_when(teamname %in% c("California Angels",
                                                        "Anahaim Angels",
                                                        "Los Angeles Angels of Anaheim") ~
                                                          "Los Angeles Angels",
                                        TRUE ~ teamname))) %>%
  arrange(year) %>%
  group_by(player_id) %>%
  mutate(draft_numb = row_number()) %>%
  ungroup()

# deleting useless columns

master$mlbid_1 <- NULL
master$x27 <- NULL

```


```{r, echo=FALSE}
draft_2000_2012 <- draft %>%
  filter(year >= 2000 & year <= 2012)

draft_2000_2012 <- draft_2000_2012 %>%
  mutate(mlb_made = ifelse(high_level == "MLB", 1, 0)) %>%
  mutate(ignore = 1) %>%
  group_by(draft_round) %>%
  summarize(percent_mlb = sum(mlb_made) / sum(ignore))

ggplot(draft_2000_2012, mapping = aes(draft_round, percent_mlb)) +
  geom_col() +
  theme_economist_white() +
  labs(
    x = "Draft Round",
    y = "Percent to reach Major Leagues",
    title = "Percent of Draft Picks by Round to Reach the Majors",
    subtitle = "Data from 2000-2012 drafts"
  ) 
```

```{r, echo=FALSE}
grow_talent <- master %>%
  filter(source == "H" & signed == "Y") %>%
  mutate(decade = ifelse(year %in% 1970:1979, 1970,
                                 ifelse(year %in% 1980:1989, 1980,
                                        ifelse(year %in% 1990:1999, 1990,
                                               ifelse(year %in% 2000:2009, 2000,
                                                      ifelse(year %in% 2010:2019, 2010, NA)))))) %>%
  filter(year >= 1980 & year <= 2009) %>%
  mutate(mlb_made = ifelse(high_level == "MLB", 1, 0)) %>%
  mutate(ignore = 1) %>%
  group_by(teamname) %>%
  summarize(percent_mlb = sum(mlb_made) / sum(ignore))

ggplot(grow_talent, mapping = aes(x = reorder(teamname, -percent_mlb), percent_mlb)) +
  geom_col() +
  theme_economist_white() +
  theme(axis.text.x = element_text(angle = 90)) +
  labs(
    x = "Team",
    y = "Percent of High School Picks to MLB",
    title = "Percent of High School Picks to MLB by Team",
    subtitle = "Data: 1980-2009 Drafts"
  )
  
```



```{r, echo=FALSE}

hs_signed <- master %>%
  filter(source == "H" & signed == "Y") %>%
  mutate(mlb_made = ifelse(high_level == "MLB", 1, 0)) 


hs_signed_90_09 <- hs_signed %>%
  mutate(ignore = 1) %>%
  group_by(draft_round) %>%
  filter(year >= 1990 & year <= 2009) %>%
  filter(draft_round <= 40) %>%
  summarize(percent_mlb = sum(mlb_made) / sum(ignore))

ggplot(hs_signed_90_09, mapping = aes(draft_round, percent_mlb)) +
  geom_col() +
  theme_economist_white() +
  theme(axis.text.x = element_text(angle = 90)) +
  labs(
    x = "Round",
    y = "Percent of Signed High School Picks to MLB",
    title = "Percent of Signed High School Picks to MLB by Round",
    subtitle = "Data: 1980-2009 Drafts"
  )

```

```{r}

# I made a new dataset where I filtered the master set for only unsigned
# highschool picks. I only selected the player_id column. I wanted to do this so
# that I could have a list of IDs and then rejoin these player IDs using a
# left_join to keep only the data from players who did not sign out of high
# school, but all years of their draft data rather than just the draft they
# turned down out of high school. That is what hs_unsigned_full is.

list_unsigned_id <- master %>%
  filter(source == "H" & signed == "N") %>%
  select(player_id)

hs_unsigned <- hs_unsigned_list_ids %>%
  left_join(master, by = "player_id") %>%
  arrange(player_id, desc(year))
```


```{r}

# filtered the data of unsigned high school picks with their subsequent drafts
# for only the first instance of the player being drafted, which is the draft
# afte their senior year of high school. For count_redrafted_hs, I filtered for
# draft_numb equal to 2 to see how many players were redrafted after originally
# turning the draft down.

count_unsigned_hs <- hs_unsigned_full %>%
  filter(draft_numb == 1) %>%
  count() %>%
  pull(n)

count_redrafted_hs <- hs_unsigned_full %>%
  filter(draft_numb == 2) %>%
  count() %>%
  pull(n)

percent_redrafted_hs <- round(count_redrafted_hs / (count_unsigned_hs), 2)


# below, I repeat the same process for high school players drafted in the top 10 and 20 rounds

```




















